name: autofix.ci

on: [push, pull_request]

jobs:
  autofix:
    name: Autofix

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ubuntu-latest-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ubuntu-latest-rubygems-

      - name: Fix style issues
        run: brew style jonahsnider/tap --fix

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
