name: Automerge

on:
  workflow_run:
    workflows:
      - brew test-bot
    types:
      - completed

jobs:
  automerge:
    permissions:
      actions: write
      contents: read
      issues: read
      pull-requests: read
    uses: ./.github/workflows/homebrew-automerge-reusable.yml
