name: brew pr-pull

run-name: "brew pr-pull #${{ inputs.pull_request }}"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.pull_request }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      head_sha:
        description: Expected pull request head commit SHA (optional)
      warn_on_upload_failure:
        description: Continue if bottle upload fails (optional)
        default: false
        required: false
        type: boolean

jobs:
  pr-pull:
    permissions:
      actions: read
      checks: read
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/homebrew-publish-reusable.yml
    with:
      app_client_id: ${{ vars.BREW_COMMIT_CLIENT_ID }}
      head_sha: ${{ inputs.head_sha }}
      pull_request: ${{ inputs.pull_request }}
      warn_on_upload_failure: ${{ inputs.warn_on_upload_failure }}
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
