name: Update package versions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update package versions

    runs-on: macos-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - name: List formulae in tap
        id: list-formulae
        run: |
          formulae=$(find Formula -maxdepth 1 -name "*.rb" -type f -exec basename {} .rb \; | sed 's/^/jonahsnider\/tap\//' | tr '\n' ' ')
          echo "formulae=$formulae" >> "$GITHUB_OUTPUT"
      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          formulae: ${{ steps.list-formulae.outputs.formulae }}
          fork: false

